export const COLLEGES = [
    // IITs (Indian Institutes of Technology)
    "Indian Institute of Technology Bombay",
    "IIT Bombay",
    "Indian Institute of Technology Delhi",
    "IIT Delhi",
    "Indian Institute of Technology Madras",
    "IIT Madras",
    "Indian Institute of Technology Kanpur",
    "IIT Kanpur",
    "Indian Institute of Technology Kharagpur",
    "IIT Kharagpur",
    "Indian Institute of Technology Roorkee",
    "IIT Roorkee",
    "Indian Institute of Technology Guwahati",
    "IIT Guwahati",
    "Indian Institute of Technology Hyderabad",
    "IIT Hyderabad",
    "Indian Institute of Technology Indore",
    "IIT Indore",
    "Indian Institute of Technology BHU",
    "IIT BHU Varanasi",
    "Indian Institute of Technology Bhubaneswar",
    "IIT Bhubaneswar",
    "Indian Institute of Technology Gandhinagar",
    "IIT Gandhinagar",
    "Indian Institute of Technology Patna",
    "IIT Patna",
    "Indian Institute of Technology Ropar",
    "IIT Ropar",
    "Indian Institute of Technology Mandi",
    "IIT Mandi",
    "Indian Institute of Technology Jodhpur",
    "IIT Jodhpur",
    "Indian Institute of Technology Tirupati",
    "IIT Tirupati",
    "Indian Institute of Technology Palakkad",
    "IIT Palakkad",
    "Indian Institute of Technology Bhilai",
    "IIT Bhilai",
    "Indian Institute of Technology Goa",
    "IIT Goa",
    "Indian Institute of Technology Jammu",
    "IIT Jammu",
    "Indian Institute of Technology Dharwad",
    "IIT Dharwad",
    
    // NITs (National Institutes of Technology)
    "National Institute of Technology Trichy",
    "NIT Trichy",
    "NIT Tiruchirappalli",
    "National Institute of Technology Surathkal",
    "NIT Surathkal",
    "NITK Surathkal",
    "National Institute of Technology Warangal",
    "NIT Warangal",
    "National Institute of Technology Rourkela",
    "NIT Rourkela",
    "National Institute of Technology Karnataka",
    "NIT Karnataka",
    "National Institute of Technology Calicut",
    "NIT Calicut",
    "National Institute of Technology Durgapur",
    "NIT Durgapur",
    "National Institute of Technology Jaipur",
    "NIT Jaipur",
    "National Institute of Technology Kurukshetra",
    "NIT Kurukshetra",
    "National Institute of Technology Nagpur",
    "NIT Nagpur",
    "National Institute of Technology Silchar",
    "NIT Silchar",
    "National Institute of Technology Allahabad",
    "NIT Allahabad",
    "National Institute of Technology Bhopal",
    "NIT Bhopal",
    "National Institute of Technology Hamirpur",
    "NIT Hamirpur",
    "National Institute of Technology Jalandhar",
    "NIT Jalandhar",
    "National Institute of Technology Patna",
    "NIT Patna",
    "National Institute of Technology Raipur",
    "NIT Raipur",
    "National Institute of Technology Srinagar",
    "NIT Srinagar",
    "National Institute of Technology Agartala",
    "NIT Agartala",
    "National Institute of Technology Arunachal Pradesh",
    "NIT Arunachal Pradesh",
    "National Institute of Technology Delhi",
    "NIT Delhi",
    "National Institute of Technology Goa",
    "NIT Goa",
    "National Institute of Technology Manipur",
    "NIT Manipur",
    "National Institute of Technology Meghalaya",
    "NIT Meghalaya",
    "National Institute of Technology Mizoram",
    "NIT Mizoram",
    "National Institute of Technology Nagaland",
    "NIT Nagaland",
    "National Institute of Technology Puducherry",
    "NIT Puducherry",
    "National Institute of Technology Sikkim",
    "NIT Sikkim",
    "National Institute of Technology Uttarakhand",
    "NIT Uttarakhand",
    "National Institute of Technology Andhra Pradesh",
    "NIT Andhra Pradesh",
    
    // IIITs (Indian Institutes of Information Technology)
    "IIIT Hyderabad",
    "International Institute of Information Technology Hyderabad",
    "IIIT Bangalore",
    "International Institute of Information Technology Bangalore",
    "IIIT Delhi",
    "Indraprastha Institute of Information Technology Delhi",
    "IIIT Allahabad",
    "Indian Institute of Information Technology Allahabad",
    "IIIT Gwalior",
    "ABV-IIITM Gwalior",
    "IIIT Jabalpur",
    "IIITDM Jabalpur",
    "IIIT Kancheepuram",
    "IIITDM Kancheepuram",
    "IIIT Kottayam",
    "Indian Institute of Information Technology Kottayam",
    "IIIT Pune",
    "Indian Institute of Information Technology Pune",
    "IIIT Vadodara",
    "Indian Institute of Information Technology Vadodara",
    "IIIT Kota",
    "Indian Institute of Information Technology Kota",
    "IIIT Nagpur",
    "Indian Institute of Information Technology Nagpur",
    "IIIT Sri City",
    "Indian Institute of Information Technology Sri City",
    "IIIT Lucknow",
    "Indian Institute of Information Technology Lucknow",
    
    // IIMs (Indian Institutes of Management)
    "Indian Institute of Management Ahmedabad",
    "IIM Ahmedabad",
    "Indian Institute of Management Bangalore",
    "IIM Bangalore",
    "Indian Institute of Management Calcutta",
    "IIM Calcutta",
    "Indian Institute of Management Lucknow",
    "IIM Lucknow",
    "Indian Institute of Management Kozhikode",
    "IIM Kozhikode",
    "Indian Institute of Management Indore",
    "IIM Indore",
    "Indian Institute of Management Shillong",
    "IIM Shillong",
    "Indian Institute of Management Rohtak",
    "IIM Rohtak",
    "Indian Institute of Management Ranchi",
    "IIM Ranchi",
    "Indian Institute of Management Raipur",
    "IIM Raipur",
    "Indian Institute of Management Trichy",
    "IIM Trichy",
    "Indian Institute of Management Udaipur",
    "IIM Udaipur",
    "Indian Institute of Management Kashipur",
    "IIM Kashipur",
    "Indian Institute of Management Nagpur",
    "IIM Nagpur",
    "Indian Institute of Management Visakhapatnam",
    "IIM Visakhapatnam",
    "Indian Institute of Management Amritsar",
    "IIM Amritsar",
    "Indian Institute of Management Bodh Gaya",
    "IIM Bodh Gaya",
    "Indian Institute of Management Sambalpur",
    "IIM Sambalpur",
    "Indian Institute of Management Sirmaur",
    "IIM Sirmaur",
    "Indian Institute of Management Jammu",
    "IIM Jammu",
    
    // BITS
    "Birla Institute of Technology and Science Pilani",
    "BITS Pilani",
    "BITS Pilani Goa Campus",
    "BITS Pilani Hyderabad Campus",
    "BITS Pilani K K Birla Goa Campus",
    "BITS Pilani Dubai Campus",
    
    // State Universities - Karnataka
    "Bangalore Institute of Technology",
    "BIT Bangalore",
    "BMS College of Engineering",
    "BMSCE Bangalore",
    "RV College of Engineering",
    "RVCE Bangalore",
    "PES University",
    "PES Institute of Technology",
    "M S Ramaiah Institute of Technology",
    "MSRIT Bangalore",
    "Dayananda Sagar College of Engineering",
    "DSCE Bangalore",
    "JSS Science and Technology University",
    "JSS STU Mysore",
    "Manipal Institute of Technology",
    "MIT Manipal",
    "National Institute of Technology Karnataka",
    "NITK Surathkal",
    "BMS Institute of Technology",
    "BMSIT Bangalore",
    "Sir M Visvesvaraya Institute of Technology",
    "Sir MVIT Bangalore",
    "New Horizon College of Engineering",
    "NHCE Bangalore",
    "CMR Institute of Technology",
    "CMRIT Bangalore",
    "Ramaiah Institute of Technology",
    "RIT Bangalore",
    
    // State Universities - Tamil Nadu
    "Anna University",
    "College of Engineering Guindy",
    "CEG Anna University",
    "PSG College of Technology",
    "PSG Tech Coimbatore",
    "Thiagarajar College of Engineering",
    "TCE Madurai",
    "Coimbatore Institute of Technology",
    "CIT Coimbatore",
    "SSN College of Engineering",
    "SSNCE Chennai",
    "SRM Institute of Science and Technology",
    "SRM University",
    "SRM IST",
    "Vellore Institute of Technology",
    "VIT Vellore",
    "VIT Chennai",
    "VIT Bhopal",
    "VIT Andhra Pradesh",
    "Amrita Vishwa Vidyapeetham",
    "Amrita University",
    "Amrita School of Engineering",
    "Kalasalingam Academy of Research and Education",
    "Kalasalingam University",
    "Kumaraguru College of Technology",
    "KCT Coimbatore",
    "Sri Sivasubramaniya Nadar College of Engineering",
    "Madras Institute of Technology",
    "MIT Anna University",
    
    // State Universities - Maharashtra
    "College of Engineering Pune",
    "COEP Pune",
    "Veermata Jijabai Technological Institute",
    "VJTI Mumbai",
    "Institute of Chemical Technology",
    "ICT Mumbai",
    "Sardar Patel College of Engineering",
    "SPCE Mumbai",
    "Walchand College of Engineering",
    "WCE Sangli",
    "Vishwakarma Institute of Technology",
    "VIT Pune",
    "Pune Institute of Computer Technology",
    "PICT Pune",
    "Maharashtra Institute of Technology",
    "MIT Pune",
    "College of Engineering Nashik",
    "Government College of Engineering Aurangabad",
    "K J Somaiya College of Engineering",
    "KJSCE Mumbai",
    "Thadomal Shahani Engineering College",
    "TSEC Mumbai",
    "D J Sanghvi College of Engineering",
    "DJSCE Mumbai",
    "Fr. Conceicao Rodrigues College of Engineering",
    "CRCE Mumbai",
    
    // State Universities - Delhi NCR
    "Delhi Technological University",
    "DTU Delhi",
    "Netaji Subhas University of Technology",
    "NSUT Delhi",
    "NSIT Delhi",
    "Indira Gandhi Delhi Technical University for Women",
    "IGDTUW Delhi",
    "Jamia Millia Islamia",
    "JMI Delhi",
    "Guru Gobind Singh Indraprastha University",
    "GGSIPU Delhi",
    "Bharati Vidyapeeth's College of Engineering",
    "BVCOE Delhi",
    "Maharaja Surajmal Institute of Technology",
    "MSIT Delhi",
    "Ambedkar Institute of Advanced Communication Technologies and Research",
    "AIACTR Delhi",
    
    // State Universities - Haryana
    "National Institute of Technology Kurukshetra",
    "NIT Kurukshetra",
    "Thapar Institute of Engineering and Technology",
    "Thapar University Patiala",
    "PEC University of Technology",
    "Punjab Engineering College Chandigarh",
    "Guru Jambheshwar University of Science and Technology",
    "GJUST Hisar",
    "Deenbandhu Chhotu Ram University of Science and Technology",
    "DCRUST Murthal",
    
    // State Universities - Uttar Pradesh
    "Harcourt Butler Technical University",
    "HBTU Kanpur",
    "Motilal Nehru National Institute of Technology",
    "MNNIT Allahabad",
    "Institute of Engineering and Technology Lucknow",
    "IET Lucknow",
    "Aligarh Muslim University",
    "AMU Aligarh",
    "Indian Institute of Information Technology Allahabad",
    "IIIT Allahabad",
    "Jaypee Institute of Information Technology",
    "JIIT Noida",
    "Amity University",
    "Amity Noida",
    "Galgotias University",
    "Greater Noida",
    "Shiv Nadar University",
    "SNU Greater Noida",
    "JSS Academy of Technical Education",
    "JSS Noida",
    
    // State Universities - West Bengal
    "Jadavpur University",
    "JU Kolkata",
    "Indian Institute of Engineering Science and Technology",
    "IIEST Shibpur",
    "Bengal Engineering and Science University",
    "Kalyani Government Engineering College",
    "KGEC Kalyani",
    "Jalpaiguri Government Engineering College",
    "JGEC Jalpaiguri",
    "Maulana Abul Kalam Azad University of Technology",
    "MAKAUT West Bengal",
    "Heritage Institute of Technology",
    "HIT Kolkata",
    "Netaji Subhash Engineering College",
    "NSEC Kolkata",
    
    // State Universities - Andhra Pradesh & Telangana
    "Jawaharlal Nehru Technological University Hyderabad",
    "JNTU Hyderabad",
    "JNTUH",
    "Jawaharlal Nehru Technological University Kakinada",
    "JNTU Kakinada",
    "JNTUK",
    "Osmania University",
    "OU Hyderabad",
    "University College of Engineering Osmania University",
    "Andhra University College of Engineering",
    "AU Visakhapatnam",
    "Chaitanya Bharathi Institute of Technology",
    "CBIT Hyderabad",
    "Vasavi College of Engineering",
    "VCE Hyderabad",
    "CVR College of Engineering",
    "CVRE Hyderabad",
    "Gokaraju Rangaraju Institute of Engineering and Technology",
    "GRIET Hyderabad",
    "Institute of Aeronautical Engineering",
    "IARE Hyderabad",
    "Maturi Venkata Subba Rao Engineering College",
    "MVSR Hyderabad",
    
    // State Universities - Gujarat
    "Sardar Vallabhbhai National Institute of Technology Surat",
    "SVNIT Surat",
    "NIT Surat",
    "Dhirubhai Ambani Institute of Information and Communication Technology",
    "DA-IICT Gandhinagar",
    "Pandit Deendayal Petroleum University",
    "PDPU Gandhinagar",
    "Institute of Technology Nirma University",
    "Nirma University Ahmedabad",
    "LD College of Engineering",
    "LDCE Ahmedabad",
    "Sardar Patel College of Engineering",
    "SPCE Mumbai",
    
    // State Universities - Rajasthan
    "Malaviya National Institute of Technology Jaipur",
    "MNIT Jaipur",
    "NIT Jaipur",
    "Birla Institute of Technology and Science Pilani",
    "BITS Pilani Rajasthan",
    "Malviya National Institute of Technology Jaipur",
    "LNM Institute of Information Technology",
    "LNMIIT Jaipur",
    "Rajasthan Technical University",
    "RTU Kota",
    
    // State Universities - Madhya Pradesh
    "Maulana Azad National Institute of Technology Bhopal",
    "MANIT Bhopal",
    "NIT Bhopal",
    "Indian Institute of Information Technology Design and Manufacturing Jabalpur",
    "IIITDM Jabalpur",
    "Rajiv Gandhi Proudyogiki Vishwavidyalaya",
    "RGPV Bhopal",
    "Shri Govindram Seksaria Institute of Technology and Science",
    "SGSITS Indore",
    
    // State Universities - Kerala
    "National Institute of Technology Calicut",
    "NIT Calicut",
    "NITC",
    "College of Engineering Trivandrum",
    "CET Trivandrum",
    "Government Engineering College Thrissur",
    "GEC Thrissur",
    "Cochin University of Science and Technology",
    "CUSAT Kochi",
    "Model Engineering College",
    "MEC Kochi",
    "TKM College of Engineering",
    "TKMCE Kollam",
    "Rajagiri School of Engineering and Technology",
    "RSET Kochi",
    
    // State Universities - Odisha
    "National Institute of Technology Rourkela",
    "NIT Rourkela",
    "NITR",
    "International Institute of Information Technology Bhubaneswar",
    "IIIT Bhubaneswar",
    "College of Engineering and Technology Bhubaneswar",
    "CET Bhubaneswar",
    "Veer Surendra Sai University of Technology",
    "VSSUT Burla",
    
    // State Universities - Bihar
    "National Institute of Technology Patna",
    "NIT Patna",
    "NITP",
    "Indian Institute of Technology Patna",
    "IIT Patna",
    "Bihar Engineering University",
    "BEU Patna",
    "Muzaffarpur Institute of Technology",
    "MIT Muzaffarpur",
    
    // State Universities - Chhattisgarh
    "National Institute of Technology Raipur",
    "NIT Raipur",
    "NITR",
    "Bhilai Institute of Technology",
    "BIT Durg",
    
    // State Universities - Assam
    "National Institute of Technology Silchar",
    "NIT Silchar",
    "NITS",
    "Indian Institute of Technology Guwahati",
    "IIT Guwahati",
    "Assam Engineering College",
    "AEC Guwahati",
    "Jorhat Engineering College",
    "JEC Jorhat",
    
    // State Universities - Punjab
    "Thapar Institute of Engineering and Technology Patiala",
    "Thapar University",
    "Punjab Engineering College Chandigarh",
    "PEC Chandigarh",
    "Guru Nanak Dev Engineering College",
    "GNDEC Ludhiana",
    "Sant Longowal Institute of Engineering and Technology",
    "SLIET Longowal",
    
    // Private Universities
    "Lovely Professional University",
    "LPU Jalandhar",
    "Manipal Academy of Higher Education",
    "MAHE Manipal",
    "Amrita Vishwa Vidyapeetham Coimbatore",
    "Amrita University Coimbatore",
    "SASTRA Deemed University",
    "SASTRA Thanjavur",
    "Kalinga Institute of Industrial Technology",
    "KIIT Bhubaneswar",
    "Siksha 'O' Anusandhan",
    "SOA University Bhubaneswar",
    "Graphic Era University",
    "GEU Dehradun",
    "Chandigarh University",
    "CU Mohali",
    "Chitkara University",
    "Chitkara Punjab",
    "Bennett University",
    "Times of India Group Greater Noida",
    "SRM Institute of Science and Technology",
    "SRM Chennai",
    "UPES",
    "University of Petroleum and Energy Studies Dehradun",
    "Symbiosis Institute of Technology",
    "SIT Pune",
    "Christ University",
    "Christ Bangalore",
    "Jain University",
    "Jain Bangalore",
    "Alliance University",
    "Alliance Bangalore",
    
    // Foreign Universities Popular Among Indians
    "Stanford University",
    "Massachusetts Institute of Technology",
    "MIT",
    "Carnegie Mellon University",
    "CMU",
    "University of California Berkeley",
    "UC Berkeley",
    "Harvard University",
    "California Institute of Technology",
    "Caltech",
    "University of Michigan Ann Arbor",
    "University of Texas Austin",
    "UT Austin",
    "University of Illinois Urbana-Champaign",
    "UIUC",
    "Georgia Institute of Technology",
    "Georgia Tech",
    "Cornell University",
    "University of Southern California",
    "USC",
    "Columbia University",
    "University of Washington",
    "UW Seattle",
    "Princeton University",
    "Yale University",
    "University of Pennsylvania",
    "UPenn",
    "Duke University",
    "Northwestern University",
    "Brown University",
    "University of California Los Angeles",
    "UCLA",
    "University of California San Diego",
    "UCSD",
    "New York University",
    "NYU",
    "Boston University",
    "BU",
    "University of Wisconsin Madison",
    "Purdue University",
    "Ohio State University",
    "Texas A&M University",
    "University of Maryland",
    "UMD",
    "University of Minnesota",
    "University of California Irvine",
    "UCI",
    "Penn State University",
    "Rutgers University",
    "University of Florida",
    "UF",
    "Arizona State University",
    "ASU",
    "North Carolina State University",
    "NCSU",
    "Virginia Tech",
    "University of California Davis",
    "UC Davis",
    "University of California Santa Barbara",
    "UCSB",
    "Stony Brook University",
    "SUNY Stony Brook",
    "University of Massachusetts Amherst",
    "UMass Amherst",
    "University of Rochester",
    "Northeastern University",
    "University of Pittsburgh",
    "Michigan State University",
    "Iowa State University",
    "University of Arizona",
    "University of Colorado Boulder",
    "University of Utah",
    "University of California Riverside",
    "UCR",
    "University of Notre Dame",
    "Vanderbilt University",
    "Rice University",
    "Emory University",
    "University of Virginia",
    "UVA",
    "University of North Carolina Chapel Hill",
    "UNC",
    "University of Miami",
    "Georgetown University",
    "University of California Santa Cruz",
    "UCSC",
    "Rensselaer Polytechnic Institute",
    "RPI",
    "Worcester Polytechnic Institute",
    "WPI",
    "Case Western Reserve University",
    "CWRU",
    "University of Delaware",
    "Drexel University",
    "Syracuse University",
    "University of Connecticut",
    "UConn",
    "George Washington University",
    "GWU",
    "University of Texas Dallas",
    "UTD",
    "University of Houston",
    "UH",
    "University of South Florida",
    "USF",
    "University of Central Florida",
    "UCF",
    "Florida International University",
    "FIU",
    "San Jose State University",
    "SJSU",
    "California State University Long Beach",
    "CSULB",
    "Santa Clara University",
    "SCU",
    "Stevens Institute of Technology",
    "Illinois Institute of Technology",
    "IIT Chicago",
    "New Jersey Institute of Technology",
    "NJIT",
    "University of Texas Arlington",
    "UTA",
    "University of Kansas",
    "KU",
    "Oklahoma State University",
    "Oregon State University",
    "OSU",
    "Washington State University",
    "WSU",
    "University of Nebraska Lincoln",
    "UNL",
    "University of Iowa",
    "UI",
    "Louisiana State University",
    "LSU",
    "University of Kentucky",
    "UK",
    "University of Tennessee",
    "UT Knoxville",
    "University of Alabama",
    "UA",
    "Auburn University",
    "Clemson University",
    "University of Oklahoma",
    "OU",
    "University of Missouri",
    "Mizzou",
    "Kansas State University",
    "KSU",
    
    // UK Universities
    "University of Oxford",
    "Oxford",
    "University of Cambridge",
    "Cambridge",
    "Imperial College London",
    "University College London",
    "UCL",
    "University of Edinburgh",
    "King's College London",
    "KCL",
    "University of Manchester",
    "London School of Economics",
    "LSE",
    "University of Bristol",
    "University of Warwick",
    "University of Glasgow",
    "Durham University",
    "University of Birmingham",
    "University of Southampton",
    "University of Leeds",
    "University of Sheffield",
    "University of Nottingham",
    "Queen Mary University of London",
    "QMUL",
    "Lancaster University",
    "University of York",
    "Cardiff University",
    "University of Exeter",
    "University of Bath",
    "Newcastle University",
    "University of Liverpool",
    "University of Reading",
    "University of Surrey",
    
    // Canada Universities
    "University of Toronto",
    "U of T",
    "University of British Columbia",
    "UBC",
    "McGill University",
    "University of Alberta",
    "University of Montreal",
    "McMaster University",
    "University of Waterloo",
    "Western University",
    "University of Calgary",
    "Queen's University",
    "Simon Fraser University",
    "SFU",
    "Dalhousie University",
    "University of Ottawa",
    "University of Victoria",
    "Carleton University",
    "York University",
    "Ryerson University",
    "Toronto Metropolitan University",
    "Concordia University",
    
    // Australia Universities
    "University of Melbourne",
    "Australian National University",
    "ANU",
    "University of Sydney",
    "University of Queensland",
    "UQ",
    "University of New South Wales",
    "UNSW Sydney",
    "Monash University",
    "University of Western Australia",
    "UWA",
    "University of Adelaide",
    "University of Technology Sydney",
    "UTS",
    "Queensland University of Technology",
    "QUT",
    "RMIT University",
    "Curtin University",
    "Macquarie University",
    
    // Singapore Universities
    "National University of Singapore",
    "NUS",
    "Nanyang Technological University",
    "NTU Singapore",
    "Singapore Management University",
    "SMU",
    "Singapore University of Technology and Design",
    "SUTD",
    
    // Germany Universities
    "Technical University of Munich",
    "TUM",
    "Ludwig Maximilian University of Munich",
    "LMU Munich",
    "Heidelberg University",
    "Humboldt University of Berlin",
    "RWTH Aachen University",
    "University of Freiburg",
    "Free University of Berlin",
    "University of Tübingen",
    "University of Göttingen",
    "University of Bonn",
    "Technical University of Berlin",
    "TU Berlin",
    "Karlsruhe Institute of Technology",
    "KIT",
    
    // Other European Universities
    "ETH Zurich",
    "Swiss Federal Institute of Technology",
    "EPFL",
    "École Polytechnique Fédérale de Lausanne",
    "University of Amsterdam",
    "Delft University of Technology",
    "TU Delft",
    "KU Leuven",
    "University of Copenhagen",
    "Lund University",
    "Uppsala University",
  ];