export const COMPANIES = [
    // Indian IT Giants
    "Tata Consultancy Services",
    "TCS",
    "Infosys",
    "Wipro",
    "HCL Technologies",
    "Tech Mahindra",
    "LTI Mindtree",
    "Mphasis",
    "L&T Infotech",
    "Larsen & Toubro Infotech",
    "Persistent Systems",
    "Cyient",
    "LTTS",
    "L&T Technology Services",
    "Hexaware Technologies",
    "Zensar Technologies",
    "Sonata Software",
    "Mastek",
    "NIIT Technologies",
    "Coforge",
    
    // Global Tech Giants
    "Google",
    "Microsoft",
    "Amazon",
    "Apple",
    "Meta",
    "Facebook",
    "Netflix",
    "Adobe",
    "IBM",
    "Oracle",
    "SAP",
    "Salesforce",
    "Intel",
    "NVIDIA",
    "AMD",
    "Cisco",
    "VMware",
    "Dell Technologies",
    "HP",
    "Hewlett Packard Enterprise",
    "Qualcomm",
    "Broadcom",
    "Texas Instruments",
    "Accenture",
    "Capgemini",
    "Cognizant",
    "DXC Technology",
    "Atos",
    "NTT Data",
    "Fujitsu",
    "Hitachi",
    "Samsung",
    "LG Electronics",
    "Sony",
    "Panasonic",
    
    // Indian Startups & Unicorns
    "Flipkart",
    "PhonePe",
    "Paytm",
    "Zomato",
    "Swiggy",
    "Ola",
    "Ola Electric",
    "Byju's",
    "Unacademy",
    "upGrad",
    "Meesho",
    "CRED",
    "Razorpay",
    "Zerodha",
    "Groww",
    "BharatPe",
    "Policybazaar",
    "Nykaa",
    "Lenskart",
    "Urban Company",
    "Dunzo",
    "Udaan",
    "BigBasket",
    "Grofers",
    "Blinkit",
    "Ather Energy",
    "FirstCry",
    "Delhivery",
    "Shiprocket",
    "CarDekho",
    "CarTrade",
    "Quikr",
    "OLX India",
    "MakeMyTrip",
    "Goibibo",
    "Cleartrip",
    "redBus",
    "Oyo",
    "Treebo",
    "FabHotels",
    "Zostel",
    "ShareChat",
    "Moj",
    "Josh",
    "InMobi",
    "Glance",
    "Dream11",
    "MPL",
    "Gamezy",
    "Hike",
    "Dailyhunt",
    "VerSe Innovation",
    "Postman",
    "Freshworks",
    "Zoho",
    "Chargebee",
    "CleverTap",
    "Druva",
    "Icertis",
    "Innovaccer",
    "ThoughtSpot",
    "Browserstack",
    "Hasura",
    
    // Indian E-commerce & Retail
    "Amazon India",
    "Myntra",
    "Ajio",
    "Tata CLiQ",
    "Snapdeal",
    "ShopClues",
    "JioMart",
    "Reliance Retail",
    "Future Group",
    "Big Bazaar",
    "DMart",
    "More",
    "Spencer's Retail",
    
    // Fintech Companies
    "PhonePe",
    "Google Pay India",
    "PayTM",
    "Amazon Pay",
    "Mobikwik",
    "Freecharge",
    "HDFC Bank",
    "ICICI Bank",
    "State Bank of India",
    "SBI",
    "Axis Bank",
    "Kotak Mahindra Bank",
    "Yes Bank",
    "IndusInd Bank",
    "Federal Bank",
    "RBL Bank",
    "IDFC First Bank",
    "Bank of Baroda",
    "Punjab National Bank",
    "Canara Bank",
    
    // Indian Automotive
    "Tata Motors",
    "Mahindra & Mahindra",
    "Maruti Suzuki",
    "Hyundai India",
    "Honda India",
    "Toyota India",
    "Bajaj Auto",
    "Hero MotoCorp",
    "TVS Motor",
    "Royal Enfield",
    "Ashok Leyland",
    "Eicher Motors",
    "Force Motors",
    
    // Consulting Firms
    "McKinsey & Company",
    "Boston Consulting Group",
    "BCG",
    "Bain & Company",
    "Deloitte",
    "PwC",
    "PricewaterhouseCoopers",
    "EY",
    "Ernst & Young",
    "KPMG",
    "Grant Thornton",
    "BDO",
    "Alvarez & Marsal",
    
    // Product Companies
    "Atlassian",
    "Slack",
    "Stripe",
    "PayPal",
    "Square",
    "Shopify",
    "Uber",
    "Lyft",
    "Airbnb",
    "DoorDash",
    "Instacart",
    "Snap",
    "Snapchat",
    "Twitter",
    "X Corp",
    "LinkedIn",
    "Pinterest",
    "Reddit",
    "Discord",
    "Twitch",
    "Spotify",
    "SoundCloud",
    "Zoom",
    "Webex",
    "Dropbox",
    "Box",
    "Slack Technologies",
    
    // Gaming Companies
    "Zynga",
    "Electronic Arts",
    "EA",
    "Activision Blizzard",
    "Ubisoft",
    "Riot Games",
    "Epic Games",
    "Valve Corporation",
    "Rockstar Games",
    "Supercell",
    "Nazara Technologies",
    "Games24x7",
    "Octro",
    "Moonfrog Labs",
    
    // Indian Conglomerates
    "Tata Group",
    "Reliance Industries",
    "Aditya Birla Group",
    "Mahindra Group",
    "Godrej Group",
    "ITC Limited",
    "Larsen & Toubro",
    "L&T",
    "Bajaj Group",
    "Bharti Enterprises",
    "Essar Group",
    "JSW Group",
    "Vedanta Group",
    "Adani Group",
    
    // Telecom Companies
    "Reliance Jio",
    "Jio",
    "Airtel",
    "Bharti Airtel",
    "Vodafone Idea",
    "Vi",
    "BSNL",
    "MTNL",
    
    // Media & Entertainment
    "Zee Entertainment",
    "Sony Pictures Networks India",
    "Star India",
    "Disney+ Hotstar",
    "Viacom18",
    "Sun TV Network",
    "Network18",
    "Times Internet",
    "Times of India",
    "Hindustan Times",
    "Indian Express",
    "NDTV",
    "Republic TV",
    "India Today",
    "Aaj Tak",
    
    // Healthcare & Pharma
    "Apollo Hospitals",
    "Fortis Healthcare",
    "Max Healthcare",
    "Manipal Hospitals",
    "Narayana Health",
    "Medanta",
    "Sun Pharmaceutical",
    "Dr. Reddy's Laboratories",
    "Cipla",
    "Lupin",
    "Aurobindo Pharma",
    "Cadila Healthcare",
    "Zydus",
    "Glenmark Pharmaceuticals",
    "Biocon",
    "Divi's Laboratories",
    "Torrent Pharmaceuticals",
    "Alkem Laboratories",
    "Mankind Pharma",
    "Practo",
    "1mg",
    "PharmEasy",
    "Netmeds",
    
    // EdTech Companies
    "Byju's",
    "Unacademy",
    "Vedantu",
    "Toppr",
    "upGrad",
    "Great Learning",
    "Simplilearn",
    "Coursera India",
    "Udemy",
    "Khan Academy",
    "DoubtNut",
    "Meritnation",
    "Extramarks",
    "Physics Wallah",
    "Adda247",
    "Testbook",
    "Gradeup",
    "Embibe",
    
    // Cybersecurity Companies
    "Palo Alto Networks",
    "CrowdStrike",
    "Fortinet",
    "Check Point",
    "McAfee",
    "Symantec",
    "Norton",
    "Kaspersky",
    "Trend Micro",
    "FireEye",
    "Mandiant",
    "Zscaler",
    "Quick Heal",
    "K7 Computing",
    
    // Cloud & Infrastructure
    "DigitalOcean",
    "Linode",
    "Vultr",
    "Rackspace",
    "OVH",
    "Cloudflare",
    "Akamai",
    "Fastly",
    
    // AI/ML Companies
    "OpenAI",
    "Anthropic",
    "DeepMind",
    "Stability AI",
    "Hugging Face",
    "Cohere",
    "Scale AI",
    "DataRobot",
    "C3.ai",
    "SambaNova Systems",
    "Cerebras",
    
    // Semiconductor Companies
    "TSMC",
    "Samsung Electronics",
    "Micron Technology",
    "SK Hynix",
    "Applied Materials",
    "ASML",
    "Lam Research",
    "KLA Corporation",
    
    // Networking Companies
    "Juniper Networks",
    "Arista Networks",
    "F5 Networks",
    "Palo Alto Networks",
    "Fortinet",
    "A10 Networks",
    
    // Database Companies
    "MongoDB",
    "Redis Labs",
    "Elastic",
    "Confluent",
    "Databricks",
    "Snowflake",
    "Cockroach Labs",
    "Neo4j",
    
    // DevOps & CI/CD
    "GitLab",
    "Jenkins",
    "CircleCI",
    "Travis CI",
    "HashiCorp",
    "Terraform",
    "Ansible",
    "Chef Software",
    "Puppet",
    
    // Analytics Companies
    "Tableau",
    "Looker",
    "Domo",
    "Sisense",
    "ThoughtSpot",
    "Qlik",
    "MicroStrategy",
    
    // CRM Companies
    "Salesforce",
    "HubSpot",
    "Zoho CRM",
    "Pipedrive",
    "Freshsales",
    "SugarCRM",
    
    // E-commerce Platforms
    "Shopify",
    "WooCommerce",
    "Magento",
    "BigCommerce",
    "PrestaShop",
    
    // Payment Gateways
    "Razorpay",
    "PayU",
    "CCAvenue",
    "Instamojo",
    "Cashfree",
    "Paytm Payment Gateway",
    "BillDesk",
    
    // Logistics & Supply Chain
    "Blue Dart",
    "DTDC",
    "Gati",
    "Ecom Express",
    "Delhivery",
    "Xpressbees",
    "Shadowfax",
    "Rivigo",
    "BlackBuck",
    "Porter",
    "Loadshare",
    
    // Real Estate Tech
    "99acres",
    "Housing.com",
    "MagicBricks",
    "PropTiger",
    "NoBroker",
    "Commonfloor",
    "Nestaway",
    
    // AgriTech
    "DeHaat",
    "Ninjacart",
    "AgroStar",
    "CropIn",
    "Agrowave",
    "FarMart",
    "WayCool",
    
    // Travel Tech
    "MakeMyTrip",
    "Goibibo",
    "Yatra",
    "Ixigo",
    "EaseMyTrip",
    "Cleartrip",
    "TripAdvisor",
    
    // Job Portals
    "Naukri.com",
    "Indeed India",
    "LinkedIn India",
    "Monster India",
    "Shine.com",
    "TimesJobs",
    "Glassdoor India",
    "AngelList India",
    "Wellfound",
    "Instahyre",
    "Cutshort",
    "Hirect",
    
    // Insurance Tech
    "Policybazaar",
    "Acko",
    "Digit Insurance",
    "Go Digit",
    "Turtlemint",
    "RenewBuy",
    
    // Investment Platforms
    "Zerodha",
    "Groww",
    "Upstox",
    "Angel One",
    "5paisa",
    "ICICI Direct",
    "HDFC Securities",
    "Sharekhan",
    "Motilal Oswal",
    "Edelweiss",
    
    // Legal Tech
    "Vakilsearch",
    "LegalKart",
    "MyAdvo",
    "LawRato",
    
    // HR Tech
    "Darwinbox",
    "Keka",
    "Greytip",
    "GreytHR",
    "sumHR",
    "Zimyo",
    "PeopleStrong",
    "Talview",
    
    // Marketing Tech
    "WebEngage",
    "MoEngage",
    "CleverTap",
    "Netcore Cloud",
    "Insider",
    
    // SaaS Companies
    "Freshworks",
    "Zoho",
    "Chargebee",
    "Wingify",
    "Exotel",
    "Kaleyra",
    "Knowlarity",
    "Verloop",
    "Yellow.ai",
    "Haptik",
    
    // Aerospace & Defense
    "HAL",
    "Hindustan Aeronautics Limited",
    "ISRO",
    "DRDO",
    "BEL",
    "Bharat Electronics Limited",
    "BDL",
    "Bharat Dynamics Limited",
    "Mazagon Dock Shipbuilders",
    
    // Energy & Power
    "NTPC",
    "Power Grid Corporation",
    "Coal India",
    "ONGC",
    "Indian Oil Corporation",
    "BPCL",
    "HPCL",
    "Reliance Petroleum",
    "Adani Power",
    "Tata Power",
    "JSW Energy",
    
    // Manufacturing
    "Tata Steel",
    "JSW Steel",
    "Hindalco",
    "Vedanta",
    "UltraTech Cement",
    "Ambuja Cement",
    "ACC Cement",
    "Shree Cement",
    
    // FMCG
    "Hindustan Unilever",
    "HUL",
    "ITC Limited",
    "Nestle India",
    "Britannia Industries",
    "Dabur India",
    "Marico",
    "Godrej Consumer Products",
    "Emami",
    "Patanjali Ayurved",
    "Amul",
    "Mother Dairy",
    
    // Beverages
    "Coca-Cola India",
    "PepsiCo India",
    "Parle Agro",
    "Bisleri",
    "Tropicana",
    "Paper Boat",
    "Hector Beverages",
    
    // Fashion & Apparel
    "Raymond",
    "Aditya Birla Fashion",
    "Louis Philippe",
    "Van Heusen",
    "Allen Solly",
    "Peter England",
    "Pantaloons",
    "Westside",
    "Max Fashion",
    "FabIndia",
    "Biba",
    "W",
    "Manyavar",
    
    // Footwear
    "Bata India",
    "Relaxo Footwears",
    "Liberty Shoes",
    "Woodland",
    "Red Tape",
    "Metro Shoes",
    
    // Jewelry
    "Tanishq",
    "Malabar Gold",
    "Kalyan Jewellers",
    "PC Jeweller",
    "Senco Gold",
    "Joyalukkas",
  ];