export const DEGREES = [
    // Undergraduate Degrees - Engineering
    "Bachelor of Technology",
    "B.Tech",
    "Bachelor of Engineering",
    "B.E.",
    "B.Tech in Computer Science and Engineering",
    "B.Tech CSE",
    "B.Tech in Information Technology",
    "B.Tech IT",
    "B.Tech in Electronics and Communication Engineering",
    "B.Tech ECE",
    "B.Tech in Electrical Engineering",
    "B.Tech EE",
    "B.Tech in Electrical and Electronics Engineering",
    "B.Tech EEE",
    "B.Tech in Mechanical Engineering",
    "B.Tech ME",
    "B.Tech in Civil Engineering",
    "B.Tech CE",
    "B.Tech in Chemical Engineering",
    "B.Tech in Biotechnology",
    "B.Tech in Aerospace Engineering",
    "B.Tech in Automobile Engineering",
    "B.Tech in Production Engineering",
    "B.Tech in Industrial Engineering",
    "B.Tech in Instrumentation Engineering",
    "B.Tech in Petroleum Engineering",
    "B.Tech in Mining Engineering",
    "B.Tech in Metallurgical Engineering",
    "B.Tech in Agricultural Engineering",
    "B.Tech in Food Technology",
    "B.Tech in Textile Engineering",
    "B.Tech in Environmental Engineering",
    "B.Tech in Biomedical Engineering",
    "B.Tech in Robotics and Automation",
    "B.Tech in Artificial Intelligence",
    "B.Tech AI",
    "B.Tech in Machine Learning",
    "B.Tech in Data Science",
    "B.Tech in Cyber Security",
    "B.Tech in Cloud Computing",
    "B.Tech in Internet of Things",
    "B.Tech IoT",
    "B.Tech in Blockchain Technology",
    
    // Undergraduate Degrees - Science
    "Bachelor of Science",
    "B.Sc",
    "B.Sc in Computer Science",
    "B.Sc CS",
    "B.Sc in Information Technology",
    "B.Sc IT",
    "B.Sc in Physics",
    "B.Sc in Chemistry",
    "B.Sc in Mathematics",
    "B.Sc in Statistics",
    "B.Sc in Biology",
    "B.Sc in Biotechnology",
    "B.Sc in Microbiology",
    "B.Sc in Biochemistry",
    "B.Sc in Electronics",
    "B.Sc in Zoology",
    "B.Sc in Botany",
    "B.Sc in Environmental Science",
    "B.Sc in Data Science",
    "B.Sc in Artificial Intelligence",
    "B.Sc in Animation",
    "B.Sc in Multimedia",
    "B.Sc in Agriculture",
    "B.Sc in Forestry",
    "B.Sc in Horticulture",
    "B.Sc in Nursing",
    "B.Sc in Medical Laboratory Technology",
    "B.Sc MLT",
    
    // Undergraduate Degrees - Computer Applications
    "Bachelor of Computer Applications",
    "BCA",
    "Bachelor of Information Technology",
    "BIT",
    
    // Undergraduate Degrees - Commerce & Management
    "Bachelor of Commerce",
    "B.Com",
    "Bachelor of Business Administration",
    "BBA",
    "Bachelor of Management Studies",
    "BMS",
    "Bachelor of Business Management",
    "BBM",
    "Bachelor of Financial Markets",
    "BFM",
    "Bachelor of Accounting and Finance",
    "BAF",
    "Bachelor of Banking and Insurance",
    "BBI",
    
    // Undergraduate Degrees - Arts & Humanities
    "Bachelor of Arts",
    "B.A",
    "B.A in English",
    "B.A in Economics",
    "B.A in Psychology",
    "B.A in Sociology",
    "B.A in Political Science",
    "B.A in History",
    "B.A in Geography",
    "B.A in Philosophy",
    "B.A in Journalism",
    "B.A in Mass Communication",
    
    // Undergraduate Degrees - Design
    "Bachelor of Design",
    "B.Des",
    "Bachelor of Fine Arts",
    "BFA",
    "Bachelor of Fashion Design",
    "Bachelor of Interior Design",
    "Bachelor of Product Design",
    "Bachelor of Graphic Design",
    
    // Undergraduate Degrees - Architecture
    "Bachelor of Architecture",
    "B.Arch",
    
    // Undergraduate Degrees - Pharmacy
    "Bachelor of Pharmacy",
    "B.Pharm",
    
    // Undergraduate Degrees - Law
    "Bachelor of Laws",
    "LLB",
    "B.A LLB",
    "B.Com LLB",
    "BBA LLB",
    
    // Undergraduate Degrees - Medicine
    "Bachelor of Medicine and Bachelor of Surgery",
    "MBBS",
    "Bachelor of Dental Surgery",
    "BDS",
    "Bachelor of Ayurvedic Medicine and Surgery",
    "BAMS",
    "Bachelor of Homeopathic Medicine and Surgery",
    "BHMS",
    "Bachelor of Physiotherapy",
    "BPT",
    "Bachelor of Occupational Therapy",
    "BOT",
    
    // Postgraduate Degrees - Engineering & Technology
    "Master of Technology",
    "M.Tech",
    "Master of Engineering",
    "M.E.",
    "M.Tech in Computer Science and Engineering",
    "M.Tech CSE",
    "M.Tech in Information Technology",
    "M.Tech IT",
    "M.Tech in Electronics and Communication Engineering",
    "M.Tech ECE",
    "M.Tech in Electrical Engineering",
    "M.Tech EE",
    "M.Tech in Mechanical Engineering",
    "M.Tech ME",
    "M.Tech in Civil Engineering",
    "M.Tech CE",
    "M.Tech in Chemical Engineering",
    "M.Tech in Biotechnology",
    "M.Tech in Structural Engineering",
    "M.Tech in VLSI Design",
    "M.Tech in Embedded Systems",
    "M.Tech in Computer Networks",
    "M.Tech in Software Engineering",
    "M.Tech in Artificial Intelligence",
    "M.Tech AI",
    "M.Tech in Machine Learning",
    "M.Tech ML",
    "M.Tech in Data Science",
    "M.Tech in Cyber Security",
    "M.Tech in Cloud Computing",
    "M.Tech in Internet of Things",
    "M.Tech IoT",
    "M.Tech in Robotics",
    "M.Tech in Power Systems",
    "M.Tech in Power Electronics",
    "M.Tech in Control Systems",
    "M.Tech in Signal Processing",
    "M.Tech in Communication Systems",
    "M.Tech in Thermal Engineering",
    "M.Tech in Production Engineering",
    "M.Tech in CAD/CAM",
    "M.Tech in Automobile Engineering",
    "M.Tech in Environmental Engineering",
    "M.Tech in Nanotechnology",
    
    // Postgraduate Degrees - Science
    "Master of Science",
    "M.Sc",
    "M.Sc in Computer Science",
    "M.Sc CS",
    "M.Sc in Information Technology",
    "M.Sc IT",
    "M.Sc in Physics",
    "M.Sc in Chemistry",
    "M.Sc in Mathematics",
    "M.Sc in Statistics",
    "M.Sc in Biology",
    "M.Sc in Biotechnology",
    "M.Sc in Microbiology",
    "M.Sc in Biochemistry",
    "M.Sc in Electronics",
    "M.Sc in Zoology",
    "M.Sc in Botany",
    "M.Sc in Environmental Science",
    "M.Sc in Data Science",
    "M.Sc in Artificial Intelligence",
    "M.Sc in Machine Learning",
    "M.Sc in Bioinformatics",
    "M.Sc in Geology",
    "M.Sc in Geography",
    
    // Postgraduate Degrees - Computer Applications
    "Master of Computer Applications",
    "MCA",
    "Master of Information Technology",
    "MIT",
    
    // Postgraduate Degrees - Business & Management
    "Master of Business Administration",
    "MBA",
    "MBA in Finance",
    "MBA in Marketing",
    "MBA in Human Resources",
    "MBA HR",
    "MBA in Operations Management",
    "MBA in Information Technology",
    "MBA IT",
    "MBA in Healthcare Management",
    "MBA in International Business",
    "MBA in Business Analytics",
    "MBA in Data Science",
    "MBA in Digital Marketing",
    "MBA in Supply Chain Management",
    "MBA in Entrepreneurship",
    "MBA in Strategy",
    "MBA in Consulting",
    "MBA in Financial Management",
    "MBA in Investment Banking",
    "MBA in Risk Management",
    "MBA in Project Management",
    "Master of Management Studies",
    "MMS",
    "Post Graduate Diploma in Management",
    "PGDM",
    "Executive MBA",
    "EMBA",
    "Master of Finance",
    "M.Fin",
    "Master of Financial Management",
    "MFM",
    
    // Postgraduate Degrees - Commerce
    "Master of Commerce",
    "M.Com",
    "M.Com in Accounting",
    "M.Com in Finance",
    "M.Com in Taxation",
    
    // Postgraduate Degrees - Arts & Social Sciences
    "Master of Arts",
    "M.A",
    "M.A in English",
    "M.A in Economics",
    "M.A in Psychology",
    "M.A in Sociology",
    "M.A in Political Science",
    "M.A in History",
    "M.A in Geography",
    "M.A in Philosophy",
    "M.A in Journalism",
    "M.A in Mass Communication",
    "M.A in Public Administration",
    "M.A in Development Studies",
    "Master of Social Work",
    "MSW",
    
    // Postgraduate Degrees - Design
    "Master of Design",
    "M.Des",
    "Master of Fine Arts",
    "MFA",
    
    // Postgraduate Degrees - Architecture
    "Master of Architecture",
    "M.Arch",
    "Master of Planning",
    "M.Plan",
    "Master of Urban Planning",
    "MUP",
    
    // Postgraduate Degrees - Pharmacy
    "Master of Pharmacy",
    "M.Pharm",
    
    // Postgraduate Degrees - Law
    "Master of Laws",
    "LLM",
    "LLM in Corporate Law",
    "LLM in International Law",
    "LLM in Intellectual Property Law",
    "LLM in Criminal Law",
    "LLM in Constitutional Law",
    
    // Postgraduate Degrees - Medicine
    "Doctor of Medicine",
    "MD",
    "Master of Surgery",
    "MS",
    "Master of Dental Surgery",
    "MDS",
    "Master of Public Health",
    "MPH",
    "Master of Hospital Administration",
    "MHA",
    
    // Doctoral Degrees
    "Doctor of Philosophy",
    "Ph.D",
    "Ph.D in Computer Science",
    "Ph.D CS",
    "Ph.D in Electrical Engineering",
    "Ph.D in Mechanical Engineering",
    "Ph.D in Civil Engineering",
    "Ph.D in Chemical Engineering",
    "Ph.D in Electronics Engineering",
    "Ph.D in Mathematics",
    "Ph.D in Physics",
    "Ph.D in Chemistry",
    "Ph.D in Biology",
    "Ph.D in Biotechnology",
    "Ph.D in Management",
    "Ph.D in Economics",
    "Ph.D in Psychology",
    "Ph.D in Sociology",
    "Ph.D in Political Science",
    "Ph.D in History",
    "Ph.D in English Literature",
    "Ph.D in Environmental Science",
    "Ph.D in Data Science",
    "Ph.D in Artificial Intelligence",
    "Ph.D in Machine Learning",
    
    // Professional Degrees
    "Chartered Accountant",
    "CA",
    "Company Secretary",
    "CS",
    "Cost and Management Accountant",
    "CMA",
    "Chartered Financial Analyst",
    "CFA",
    "Certified Public Accountant",
    "CPA",
    "Fellow of Institute of Actuaries",
    "FIA",
    "Associate of Institute of Actuaries",
    "AIA",
    "Project Management Professional",
    "PMP",
    "Certified Information Systems Security Professional",
    "CISSP",
    "Certified Ethical Hacker",
    "CEH",
    "AWS Certified Solutions Architect",
    "Microsoft Certified Solutions Expert",
    "MCSE",
    "Cisco Certified Network Professional",
    "CCNP",
    "Cisco Certified Network Associate",
    "CCNA",
    "Certified Kubernetes Administrator",
    "CKA",
    
    // Diploma Programs
    "Diploma in Engineering",
    "Diploma in Computer Science",
    "Diploma in Electronics",
    "Diploma in Mechanical Engineering",
    "Diploma in Civil Engineering",
    "Diploma in Electrical Engineering",
    "Diploma in Information Technology",
    "Diploma in Automobile Engineering",
    "Diploma in Architecture",
    "Post Graduate Diploma in Computer Applications",
    "PGDCA",
    "Post Graduate Diploma in Business Administration",
    "PGDBA",
    "Post Graduate Diploma in Data Science",
    "Post Graduate Diploma in Artificial Intelligence",
    "Post Graduate Diploma in Digital Marketing",
    "Post Graduate Diploma in Project Management",
    "Post Graduate Diploma in Human Resource Management",
    "Post Graduate Diploma in Financial Management",
    "Post Graduate Diploma in Supply Chain Management",
    
    // International Degrees
    "Master of Science in Computer Science",
    "MSCS",
    "Master of Science in Data Science",
    "MSDS",
    "Master of Science in Electrical Engineering",
    "MSEE",
    "Master of Science in Mechanical Engineering",
    "MSME",
    "Master of Science in Information Systems",
    "MSIS",
    "Master of Science in Software Engineering",
    "MSSE",
    "Master of Science in Business Analytics",
    "MSBA",
    "Master of Science in Finance",
    "MSF",
    "Master of Information Management",
    "MIM",
    "Master of Engineering Management",
    "MEM",
    "Master of Professional Studies",
    "MPS",
    "Master of Applied Science",
    "MASc",
    
    // Emerging Fields
    "Bachelor of Technology in Artificial Intelligence and Data Science",
    "B.Tech AI-DS",
    "Bachelor of Technology in Computer Science and Business Systems",
    "B.Tech CSBS",
    "Bachelor of Technology in Information and Communication Technology",
    "B.Tech ICT",
    "Master of Technology in Quantum Computing",
    "M.Tech Quantum Computing",
    "Master of Science in Quantum Technology",
    "MS Quantum Technology",
    "Bachelor of Technology in Blockchain",
    "B.Tech Blockchain",
    "Master of Technology in Blockchain",
    "M.Tech Blockchain",
    "Bachelor of Design in User Experience",
    "B.Des UX",
    "Master of Design in User Experience",
    "M.Des UX",
    "Bachelor of Science in Game Development",
    "B.Sc Game Dev",
    "Master of Science in Game Development",
    "M.Sc Game Dev",
    "Bachelor of Technology in Renewable Energy",
    "B.Tech Renewable Energy",
    "Master of Technology in Renewable Energy",
    "M.Tech Renewable Energy",
    "Bachelor of Technology in Electric Vehicle Technology",
    "B.Tech EV Technology",
    "Master of Technology in Electric Vehicle Technology",
    "M.Tech EV Technology",
  ];
  