export const SKILLS = [
    // Programming Languages
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C++",
    "C",
    "C#",
    "Go",
    "Rust",
    "PHP",
    "Ruby",
    "Swift",
    "Kotlin",
    "Scala",
    "R",
    "MATLAB",
    "Perl",
    "Dart",
    "Objective-C",
    "Shell Scripting",
    "Bash",
    "PowerShell",
    "VBA",
    "SQL",
    "PL/SQL",
    "T-SQL",
    
    // Frontend Technologies
    "HTML",
    "HTML5",
    "CSS",
    "CSS3",
    "Sass",
    "SCSS",
    "Less",
    "Tailwind CSS",
    "Bootstrap",
    "Material-UI",
    "Ant Design",
    "Chakra UI",
    "Styled Components",
    "React",
    "React.js",
    "React Native",
    "Next.js",
    "Vue.js",
    "Nuxt.js",
    "Angular",
    "AngularJS",
    "Svelte",
    "jQuery",
    "Redux",
    "Redux Toolkit",
    "MobX",
    "Zustand",
    "Recoil",
    "Context API",
    "Webpack",
    "Vite",
    "Parcel",
    "Rollup",
    "Babel",
    "ESLint",
    "Prettier",
    
    // Backend Technologies
    "Node.js",
    "Express.js",
    "NestJS",
    "Fastify",
    "Koa",
    "Django",
    "Flask",
    "FastAPI",
    "Spring Boot",
    "Spring Framework",
    "Hibernate",
    "ASP.NET",
    ".NET Core",
    "Ruby on Rails",
    "Laravel",
    "Symfony",
    "CodeIgniter",
    "Gin",
    "Echo",
    "Fiber",
    
    // Databases
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Cassandra",
    "Oracle Database",
    "Microsoft SQL Server",
    "SQLite",
    "MariaDB",
    "DynamoDB",
    "Firebase Realtime Database",
    "Firestore",
    "CouchDB",
    "Neo4j",
    "InfluxDB",
    "Elasticsearch",
    "Memcached",
    "Apache HBase",
    "Amazon Aurora",
    
    // Cloud & DevOps
    "AWS",
    "Amazon Web Services",
    "AWS EC2",
    "AWS S3",
    "AWS Lambda",
    "AWS RDS",
    "AWS CloudFront",
    "AWS ECS",
    "AWS EKS",
    "Azure",
    "Microsoft Azure",
    "Azure DevOps",
    "Google Cloud Platform",
    "GCP",
    "Google Cloud Functions",
    "Google Kubernetes Engine",
    "Docker",
    "Kubernetes",
    "Jenkins",
    "GitLab CI/CD",
    "GitHub Actions",
    "CircleCI",
    "Travis CI",
    "Terraform",
    "Ansible",
    "Chef",
    "Puppet",
    "Vagrant",
    "Nginx",
    "Apache",
    "HAProxy",
    "CI/CD",
    "Microservices",
    "Serverless",
    
    // Data Science & AI/ML
    "Machine Learning",
    "Deep Learning",
    "Artificial Intelligence",
    "Natural Language Processing",
    "NLP",
    "Computer Vision",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "scikit-learn",
    "Pandas",
    "NumPy",
    "SciPy",
    "Matplotlib",
    "Seaborn",
    "Plotly",
    "OpenCV",
    "YOLO",
    "CNN",
    "RNN",
    "LSTM",
    "Transformer Models",
    "BERT",
    "GPT",
    "LangChain",
    "Hugging Face",
    "Apache Spark",
    "PySpark",
    "Hadoop",
    "Apache Kafka",
    "Apache Flink",
    "Data Analysis",
    "Data Visualization",
    "Statistical Analysis",
    "A/B Testing",
    "Power BI",
    "Tableau",
    "Looker",
    "Google Analytics",
    
    // Mobile Development
    "Android Development",
    "iOS Development",
    "Flutter",
    "Jetpack Compose",
    "SwiftUI",
    "Ionic",
    "Xamarin",
    "Cordova",
    "PhoneGap",
    
    // Testing & Quality Assurance
    "Jest",
    "Mocha",
    "Chai",
    "Jasmine",
    "Cypress",
    "Selenium",
    "Playwright",
    "Puppeteer",
    "JUnit",
    "TestNG",
    "PyTest",
    "Postman",
    "REST Assured",
    "Load Testing",
    "Performance Testing",
    "Unit Testing",
    "Integration Testing",
    "E2E Testing",
    "Test Automation",
    "Manual Testing",
    "API Testing",
    
    // Version Control & Collaboration
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "SVN",
    "Mercurial",
    "Jira",
    "Confluence",
    "Trello",
    "Asana",
    "Slack",
    "Microsoft Teams",
    
    // Blockchain & Web3
    "Blockchain",
    "Ethereum",
    "Solidity",
    "Smart Contracts",
    "Web3.js",
    "Ethers.js",
    "Hardhat",
    "Truffle",
    "Hyperledger",
    "Polygon",
    "Binance Smart Chain",
    "NFT",
    "DeFi",
    
    // Game Development
    "Unity",
    "Unreal Engine",
    "Godot",
    "Cocos2d",
    "Three.js",
    "WebGL",
    "OpenGL",
    "DirectX",
    
    // Security
    "Cybersecurity",
    "Information Security",
    "Penetration Testing",
    "Ethical Hacking",
    "OWASP",
    "SSL/TLS",
    "OAuth",
    "JWT",
    "Authentication",
    "Authorization",
    "Encryption",
    "Firewall",
    "VPN",
    "Security Auditing",
    
    // Networking
    "TCP/IP",
    "HTTP/HTTPS",
    "REST API",
    "GraphQL",
    "gRPC",
    "WebSockets",
    "DNS",
    "Load Balancing",
    "CDN",
    "API Gateway",
    
    // System Design & Architecture
    "System Design",
    "Microservices Architecture",
    "Monolithic Architecture",
    "Event-Driven Architecture",
    "Domain-Driven Design",
    "Design Patterns",
    "SOLID Principles",
    "Clean Architecture",
    "Scalability",
    "High Availability",
    "Distributed Systems",
    "Message Queues",
    "RabbitMQ",
    "ActiveMQ",
    "Apache Pulsar",
    
    // Project Management & Methodologies
    "Agile",
    "Scrum",
    "Kanban",
    "Waterfall",
    "SAFe",
    "Lean",
    "Six Sigma",
    "PRINCE2",
    "PMP",
    "Project Management",
    "Product Management",
    "Stakeholder Management",
    
    // UI/UX Design
    "UI Design",
    "UX Design",
    "Figma",
    "Adobe XD",
    "Sketch",
    "InVision",
    "Prototyping",
    "Wireframing",
    "User Research",
    "Usability Testing",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe After Effects",
    "Adobe Premiere Pro",
    
    // ERP & Business Tools
    "SAP",
    "SAP FICO",
    "SAP MM",
    "SAP SD",
    "SAP ABAP",
    "SAP HANA",
    "Oracle ERP",
    "Salesforce",
    "ServiceNow",
    "Workday",
    "Microsoft Dynamics",
    "Zoho CRM",
    
    // Data Engineering
    "ETL",
    "Data Warehousing",
    "Data Pipeline",
    "Apache Airflow",
    "Databricks",
    "Snowflake",
    "BigQuery",
    "Redshift",
    "dbt",
    
    // Others
    "Linux",
    "Ubuntu",
    "CentOS",
    "Red Hat",
    "Unix",
    "Windows Server",
    "Technical Writing",
    "Documentation",
    "Problem Solving",
    "Critical Thinking",
    "Team Leadership",
    "Communication",
    "Public Speaking",
    "Presentation Skills",
  ];